<script setup>
// SLIDEY — trace-turn scene
//
// One per-turn beat of a kitsoki session: the state-machine map on the left
// (current room highlighted, traversed edges lit, future edges dimmed) and the
// turn's detail rows on the right (user input, oracle calls, transition, world
// diff, host calls, narration, rejections). Generated by src/trace.js; the map
// reuses the diagram-svg geometry solver (buildPanel) verbatim.
import { computed } from 'vue';
import { store } from '../store.js';
import { buildPanel } from '../svg.js';

const panel = computed(() => buildPanel(store.scene.map || { nodes: [], edges: [] }, 0));
const rows = computed(() => store.scene.rows || []);
const convo = computed(() => store.scene.convo || null);
</script>

<template>
  <div id="traceturn-region" class="scene-region active">
    <div id="traceturn-title" class="reveal" :class="{ shown: store.isRevealed('traceturn-title') }">{{ store.scene.title || '' }}</div>

    <div class="tt-body">
      <!-- Left: state-machine map -->
      <div id="traceturn-map" class="tt-map reveal" :class="{ shown: store.isRevealed('traceturn-map') }">
        <svg :viewBox="panel.viewBox" xmlns="http://www.w3.org/2000/svg" class="tt-svg" preserveAspectRatio="xMidYMid meet">
          <defs>
            <marker :id="panel.markerId" class="dsvg-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
              <path d="M 0 0 L 10 5 L 0 10 z" />
            </marker>
          </defs>
          <template v-for="(e, j) in panel.edges" :key="`e${j}`">
            <g v-if="e.type === 'gate'" class="dsvg-edge dsvg-edge-gate-edge" :class="{ 'dsvg-edge-dim': e.dim }">
              <line :x1="e.bar1.x1" :y1="e.bar1.y1" :x2="e.bar1.x2" :y2="e.bar1.y2" :class="e.barClass" />
              <line :x1="e.bar2.x1" :y1="e.bar2.y1" :x2="e.bar2.x2" :y2="e.bar2.y2" :class="e.barClass" />
              <text :class="e.textClass" :x="e.labelX" :y="e.labelY" text-anchor="middle" dominant-baseline="middle">{{ e.text }}</text>
            </g>
            <g v-else class="dsvg-edge" :class="{ 'dsvg-edge-dim': e.dim }">
              <line :x1="e.line.x1" :y1="e.line.y1" :x2="e.line.x2" :y2="e.line.y2" :marker-end="`url(#${e.markerId})`" />
              <text v-if="e.label" class="dsvg-edge-label" :x="e.labelX" :y="e.labelY" :text-anchor="e.anchor" dominant-baseline="middle">{{ e.label }}</text>
            </g>
          </template>
          <g v-for="(n, k) in panel.nodes" :key="`n${k}`" :class="n.groupClass">
            <rect :x="n.rect.x" :y="n.rect.y" :width="n.rect.w" :height="n.rect.h" rx="14" ry="14" />
            <text v-for="(t, m) in n.texts" :key="m" :class="t.cls" :x="t.x" :y="t.y" text-anchor="middle" dominant-baseline="middle">{{ t.text }}</text>
          </g>
        </svg>
      </div>

      <!-- Right: turn detail rows -->
      <div class="tt-rows">
        <div
          v-for="(r, i) in rows"
          :key="i"
          :id="`traceturn-row-${i}`"
          class="tt-row reveal"
          :class="[`tt-row-${r.kind}`, { shown: store.isRevealed(`traceturn-row-${i}`), 'tt-error': r.error }]"
        >
          <template v-if="r.kind === 'user'">
            <span class="tt-tag tt-tag-user">user</span>
            <span class="tt-text">{{ r.text }}</span>
          </template>

          <template v-else-if="r.kind === 'oracle'">
            <span class="tt-tag tt-tag-oracle">{{ r.verb }}</span>
            <span class="tt-text">{{ r.outcome }}</span>
            <span v-if="r.meta" class="tt-meta">{{ r.meta }}</span>
          </template>

          <template v-else-if="r.kind === 'transition'">
            <span class="tt-tag tt-tag-transition">{{ r.self ? 'stay' : 'move' }}</span>
            <span class="tt-text">{{ r.from }} <span class="tt-arrow">→</span> {{ r.to }}</span>
            <span v-if="r.intent" class="tt-meta">intent: {{ r.intent }}</span>
          </template>

          <template v-else-if="r.kind === 'world'">
            <span class="tt-tag tt-tag-world">world</span>
            <span class="tt-text tt-world">
              <span v-for="(c, ci) in r.changes" :key="ci" class="tt-world-change">
                <span class="tt-world-key">{{ c.key }}</span>
                <span class="tt-world-before">{{ c.before }}</span>
                <span class="tt-arrow">→</span>
                <span class="tt-world-after">{{ c.after }}</span>
              </span>
              <span v-if="r.more" class="tt-world-more">+{{ r.more }} more</span>
            </span>
          </template>

          <template v-else-if="r.kind === 'host'">
            <span class="tt-tag tt-tag-host">host</span>
            <span class="tt-text">{{ r.name }} <span :class="r.ok ? 'tt-ok' : 'tt-fail'">{{ r.ok ? '✓' : '✗' }}</span></span>
            <span v-if="r.duration" class="tt-meta">{{ r.duration }}</span>
          </template>

          <template v-else-if="r.kind === 'say'">
            <span class="tt-tag tt-tag-say">say</span>
            <span class="tt-text">{{ r.text }}</span>
          </template>

          <template v-else-if="r.kind === 'reject'">
            <span class="tt-tag tt-tag-reject">reject</span>
            <span class="tt-text">{{ r.text }}</span>
          </template>

          <template v-else-if="r.kind === 'more'">
            <span class="tt-more">{{ r.text }}</span>
          </template>
        </div>
      </div>
    </div>

    <!-- Expand step: the turn as a conversation — chat thread + event strip. -->
    <div
      v-if="convo"
      id="traceturn-detail"
      class="tt-convo reveal"
      :class="{ shown: store.isRevealed('traceturn-detail') }"
    >
      <div class="tt-convo-heading">{{ store.scene.title }}</div>

      <div class="tt-convo-thread">
        <div v-for="(m, i) in convo.messages" :key="i" class="tt-msg" :class="`tt-msg-${m.role}`">
          <template v-if="m.role === 'user'">
            <div class="tt-msg-who"><span class="tt-msg-tag tt-tag-user">user</span></div>
            <div class="tt-msg-bubble"><span v-if="m.direct" class="tt-direct">⌁ </span>{{ m.text }}</div>
          </template>

          <template v-else-if="m.role === 'say'">
            <div class="tt-msg-who"><span class="tt-msg-tag tt-tag-say">say</span></div>
            <div class="tt-msg-bubble">{{ m.text }}</div>
          </template>

          <template v-else>
            <div class="tt-msg-who">
              <span class="tt-msg-tag tt-tag-oracle">{{ m.verb }}</span>
              <span v-if="m.model" class="tt-msg-model">{{ m.model }}</span>
            </div>
            <div class="tt-msg-bubble" :class="{ 'tt-msg-structured': !m.text, 'tt-error': m.error }">
              <span v-if="m.text">{{ m.text }}</span>
              <span v-else class="tt-msg-outcome">{{ m.outcome }}</span>
            </div>
            <div v-if="m.prompt" class="tt-msg-prompt">prompt ▸ {{ m.prompt }}</div>
          </template>
        </div>
      </div>

      <div v-if="(convo.events || []).length" class="tt-convo-events">
        <div v-for="(e, i) in convo.events" :key="i" class="tt-evt" :class="`tt-evt-${e.kind}`">
          <template v-if="e.kind === 'world'">
            <span class="tt-evt-key">{{ e.key }}</span>
            <span class="tt-evt-from">{{ e.before }}</span>
            <span class="tt-arrow">→</span>
            <span class="tt-evt-to">{{ e.after }}</span>
          </template>
          <template v-else-if="e.kind === 'transition'">
            <span class="tt-evt-label">{{ e.self ? 'stay' : 'move' }}</span>
            <span class="tt-evt-to">{{ e.to }}</span>
            <span v-if="e.intent" class="tt-evt-sub">{{ e.intent }}</span>
          </template>
          <template v-else-if="e.kind === 'host'">
            <span class="tt-evt-label">host</span>
            <span class="tt-evt-to">{{ e.name }}</span>
            <span :class="e.ok ? 'tt-ok' : 'tt-fail'">{{ e.ok ? '✓' : '✗' }}</span>
          </template>
          <template v-else-if="e.kind === 'reject'">
            <span class="tt-evt-label tt-fail">{{ e.text }}</span>
          </template>
          <template v-else-if="e.kind === 'more'">
            <span class="tt-evt-more">{{ e.text }}</span>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>
