<script setup>
// SLIDEY — transcript scene
//
// A whole kitsoki session rendered as per-turn boxed cards (à la Claude Code /
// an online AI chat, but ONE TURN PER SCREEN): each card is an enclosing box
// holding the turn's user input and the assistant's replies up top, and the
// turn's mechanics (tool/host calls, world diff, rejections, the closing state
// transition) below. Generated by src/trace.js.
//
// The scene shows ONE card at a time. The renderers advance it through the
// shared reveal-step model: setState('transcript_card_<n>') sets store
// .transcriptCard, and this component renders that card. Cards after the first
// carry a "continued" marker, and cards before the last a trailing ellipsis, so
// the sequence reads as one ongoing conversation advancing turn by turn.
//
// A status row across the top is the HUD: how far through the session you are
// (turn N / M + a fill bar tied to card position) and the cumulative token spend
// by type and dollar cost through the turn on screen (the current card's
// `progress` snapshot).
import { computed } from 'vue';
import { store } from '../store.js';

const scene = computed(() => store.scene || {});
const cards = computed(() => (store.scene && store.scene.cards) || []);
const totals = computed(() => (store.scene && store.scene.totals) || null);

// The card on screen — clamped to a valid index. Reveals drive store.transcriptCard.
const idx = computed(() => {
  const n = cards.value.length;
  if (!n) return 0;
  return Math.max(0, Math.min(n - 1, store.transcriptCard | 0));
});
const card = computed(() => cards.value[idx.value] || {});
const continues = computed(() => idx.value > 0);                       // not the first card
const hasNext = computed(() => idx.value < cards.value.length - 1);     // more turns follow
const hasEffects = computed(() => (card.value.effects || []).length > 0 || card.value.effectsMore > 0);
// A card carrying a rendered room view clamps any assistant prose harder so
// the input + the view both fit one screen.
const hasNarration = computed(() => !!card.value.roomView);
// Provenance-segmented room view: each span is LLM- or template-generated.
// Falls back to a single template span when a card has no segment data.
const roomViewSegments = computed(() => {
  if (card.value.roomViewSegments && card.value.roomViewSegments.length) return card.value.roomViewSegments;
  return card.value.roomView ? [{ llm: false, text: card.value.roomView }] : [];
});

function fmtTokens(n) {
  if (!n) return '0';
  if (n >= 1e6) return (n / 1e6).toFixed(n >= 1e7 ? 0 : 1) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(n >= 1e4 ? 0 : 1) + 'k';
  return String(n);
}
function fmtCost(c) {
  if (c == null) return '—';
  if (c === 0) return '$0';
  return c < 1 ? '$' + c.toFixed(4) : '$' + c.toFixed(2);
}

// HUD progress for the card on screen, falling back to the scene totals.
const view = computed(() => card.value.progress || {
  turn: 0, turns: (totals.value && totals.value.turns) || 0,
  input: 0, output: 0, cacheRead: 0, cacheWrite: 0, tokens: 0, cost: 0,
});
// Fill bar tracks position through the cards (last card = full).
const frac = computed(() => {
  const n = cards.value.length;
  return n > 1 ? idx.value / (n - 1) : 1;
});
const showTokens = computed(() => !!(totals.value && totals.value.haveTokens));
const showCost = computed(() => !!(totals.value && totals.value.haveCost));
</script>

<template>
  <div id="transcript-region" class="scene-region active">
    <!-- Status chrome: identity + progress through the conversation + cumulative
         spend, all on a single row. -->
    <div class="tx-hud">
      <span class="tx-hud-id">
        <b class="tx-hud-app">{{ scene.app || scene.title || '' }}</b>
        <span v-if="scene.session" class="tx-hud-sess">{{ scene.session }}</span>
      </span>
      <span class="tx-hud-turn">turn <b>{{ view.turn }}</b><span class="tx-hud-of">/ {{ view.turns }}</span></span>
      <span class="tx-hud-bar"><span class="tx-hud-fill" :style="{ width: (frac * 100).toFixed(2) + '%' }"></span></span>
      <span v-if="showTokens" class="tx-hud-tokens">
        <span class="tx-tok tx-tok-in"><span class="tx-tok-label">in</span>{{ fmtTokens(view.input) }}</span>
        <span class="tx-tok tx-tok-out"><span class="tx-tok-label">out</span>{{ fmtTokens(view.output) }}</span>
        <span class="tx-tok tx-tok-cr"><span class="tx-tok-label">cache r</span>{{ fmtTokens(view.cacheRead) }}</span>
        <span class="tx-tok tx-tok-cw"><span class="tx-tok-label">cache w</span>{{ fmtTokens(view.cacheWrite) }}</span>
      </span>
      <span v-if="showCost" class="tx-hud-cost">{{ fmtCost(view.cost) }}</span>
    </div>

    <!-- One turn, in an enclosing box. A "continued" marker on every card after
         the first carries the ongoing-conversation thread. -->
    <div id="transcript-card" class="tx-card" :class="{ 'tx-card-cont': continues, 'tx-card-q': hasNarration }">
      <div class="tx-card-head">
        <span v-if="continues" class="tx-cont">⋯ continued</span>
        <span class="tx-card-turn">turn {{ card.turn }}</span>
        <span v-if="card.room" class="tx-card-room">{{ card.room }}</span>
      </div>

      <div class="tx-card-body">
        <!-- Conversation: the user's input FIRST (a slide leads with the intent),
             then the room as it re-rendered after it, then replies / decisions. -->
        <div class="tx-conv">
          <div v-if="card.user" class="tx-msg tx-msg-user">
            <div class="tx-who">user</div>
            <div class="tx-bubble"><span v-if="card.user.direct" class="tx-direct">⌁ </span>{{ card.user.text }}</div>
          </div>

          <!-- THIS turn's rendered room view (operator-facing narration): the
               room as it re-rendered after the intent. The view that preceded
               this intent is on the previous card, so it is not repeated. -->
          <div v-if="card.roomView" class="tx-narration">
            <div class="tx-narration-label">room<span class="tx-leg"><i class="tx-leg-tpl"></i>template<i class="tx-leg-llm"></i>generated</span></div>
            <pre class="tx-narration-body"><span v-for="(s, si) in roomViewSegments" :key="si" :class="s.llm ? 'tx-seg-llm' : 'tx-seg-tpl'">{{ s.text }}</span></pre>
          </div>

          <template v-for="(f, fi) in card.flow" :key="fi">
            <div v-if="f.kind === 'assistant'" class="tx-msg tx-msg-assistant">
              <div class="tx-who">
                <span class="tx-who-tag">{{ f.tag }}</span>
                <span v-if="f.model" class="tx-who-model">{{ f.model }}</span>
              </div>
              <div class="tx-bubble">{{ f.text }}</div>
            </div>
            <div v-else class="tx-inline tx-inline-decision" :class="{ 'tx-err': f.error }">
              <span class="tx-glyph">◆</span>
              <span class="tx-inline-verb">{{ f.verb }}</span>
              <span class="tx-inline-text">{{ f.outcome }}</span>
            </div>
          </template>
        </div>

        <!-- Mechanics for the turn, below the conversation. -->
        <div v-if="hasEffects" class="tx-effects">
          <div class="tx-effects-label">tools &amp; effects</div>
          <template v-for="(e, ei) in card.effects" :key="ei">
            <div v-if="e.kind === 'tool'" class="tx-inline tx-inline-tool" :class="{ 'tx-err': !e.ok }">
              <span class="tx-glyph">●</span>
              <span class="tx-inline-verb">{{ e.name }}</span>
              <span :class="e.ok ? 'tx-ok' : 'tx-fail'">{{ e.ok ? '✓' : '✗' }}</span>
              <span v-if="e.detail" class="tx-inline-text">{{ e.detail }}</span>
              <span v-if="e.duration" class="tx-inline-meta">{{ e.duration }}</span>
            </div>
            <div v-else-if="e.kind === 'world'" class="tx-inline tx-inline-world">
              <span class="tx-glyph">Δ</span>
              <span v-for="(c, ci) in e.changes" :key="ci" class="tx-world-chip">
                <span class="tx-world-key">{{ c.key }}</span>
                <span class="tx-world-before">{{ c.before }}</span>
                <span class="tx-arrow">→</span>
                <span class="tx-world-after">{{ c.after }}</span>
              </span>
              <span v-if="e.more" class="tx-inline-meta">+{{ e.more }} more</span>
            </div>
            <div v-else-if="e.kind === 'reject'" class="tx-inline tx-inline-reject">
              <span class="tx-glyph tx-fail">⊘</span>
              <span class="tx-inline-text">{{ e.text }}</span>
            </div>
            <div v-else-if="e.kind === 'transition'" class="tx-inline tx-inline-trans" :class="{ 'tx-inline-stay': e.self }">
              <span class="tx-glyph">→</span>
              <span class="tx-inline-text">
                <template v-if="e.self">stay in <b>{{ e.to }}</b></template>
                <template v-else><b>{{ e.from }}</b> → <b>{{ e.to }}</b></template>
              </span>
              <span v-if="e.intent" class="tx-inline-meta">{{ e.intent }}</span>
            </div>
          </template>
          <div v-if="card.effectsMore" class="tx-more">+{{ card.effectsMore }} more calls</div>
        </div>
      </div>

      <!-- Trailing continuation cue: the conversation keeps going. -->
      <div v-if="hasNext" class="tx-card-next">⋯</div>
    </div>
  </div>
</template>
