/**
 * SLIDEY — trace-turn scene (one kitsoki session turn)
 *
 * Renders a state-machine map (current room highlighted, traversed edges lit)
 * beside the turn's detail rows. Generated by src/trace.js. Reveal order:
 * title → map → each detail row → hold.
 *
 * Spec:
 *   {
 *     "type": "trace-turn",
 *     "title": "turn 3  ·  clarifying",
 *     "map":   { "viewBox": "...", "nodes": [...], "edges": [...] },  // diagram-svg panel
 *     "rows":  [ { "kind": "user"|"oracle"|"transition"|"world"|"host"|"say"|"reject"|"more", ... } ],
 *     "hold":  150
 *   }
 */

'use strict';

const TIMING = require('../timing');

async function render(page, scene, ctx) {
  await page.evaluate(s => window.slidey.showTraceTurn(s), scene);
  await ctx.setState('traceturn_title');
  await ctx.setState('traceturn_map');
  for (let i = 0; i < (scene.rows || []).length; i++) {
    await ctx.setState(`traceturn_row_${i}`);
  }
  if (scene.convo && (scene.convo.messages || []).length) {
    await ctx.setState('traceturn_detail');
  }
  await ctx.hold(scene.hold ?? TIMING.traceturn_hold, 'traceturn_hold');
  await page.evaluate(() => window.slidey.hideTraceTurn());
  await ctx.hold(TIMING.inter_scene, 'inter_scene');
}

module.exports = { render };
