/**
 * SLIDEY — transcript scene (a whole kitsoki session as per-turn boxed cards)
 *
 * Renders the session as a sequence of conversation cards, ONE CARD PER TURN,
 * each fit to a single screen: the turn's user input + the assistant's replies
 * up top, the turn's mechanics (tool/host calls, world diff, rejections, the
 * closing transition) below, all inside one enclosing box. Generated by
 * src/trace.js. A status row across the top is the HUD (turn N / M + a fill bar
 * + cumulative token/cost spend through the turn on screen).
 *
 * For video we advance one card at a time, dwelling on each long enough to read
 * a turn, then hold on the final card. (The PDF exporter emits one page per
 * card via the shared reveal-step model; the web app advances one card per nav.)
 *
 * Spec:
 *   { "type": "transcript", "app": "...", "session": "...",
 *     "cards": [ { "turn", "room", "user", "flow":[...], "effects":[...], "progress" } ],
 *     "cardHold": 96, "hold": 150 }
 */

'use strict';

const TIMING = require('../timing');

async function render(page, scene, ctx) {
  await page.evaluate(s => window.slidey.showTranscript(s), scene);

  const n = (scene.cards || []).length;
  const perCard = scene.cardHold ?? TIMING.transcript_card;
  // Step through the turn cards, dwelling on each. The last card holds longer so
  // the final state of the conversation reads before the scene exits.
  for (let i = 0; i < Math.max(1, n); i++) {
    await page.evaluate(idx => window.slidey.setState(`transcript_card_${idx}`), i);
    const last = i >= n - 1;
    await ctx.hold(
      last ? (scene.hold ?? TIMING.transcript_hold) : perCard,
      last ? 'transcript_hold' : 'transcript_card'
    );
  }

  await page.evaluate(() => window.slidey.hideTranscript());
  await ctx.hold(TIMING.inter_scene, 'inter_scene');
}

module.exports = { render };
